### ISSUE TITLE
catalog files (use of sas7bcat)

### ISSUE THREAD

**Issue by vpprasanth** [JanMarvin/readsas#41]
Is there a way to add catalog files ***`(sas7bcat)`*** to read SAS data using readsas::read.sas() function?

**Comment by JanMarvin** [comment]
Hi @vpprasanth , no, at the moment this not possible. The structure of catalog files is a bit different compared to sas7bdat. It should be possible, but it's a lot of work to reverse engineer the file structure, and I don't have a use case for this. We can leave this issue open, but it's unlikely that I'll work on this any time soon or ever.

**Comment by JanMarvin** [comment]
Oh I close this, it's a duplicate of #20

**Comment by JanMarvin** [comment]
You can convert catalog files to data in sas, I remember we had to do this when we switched from a local SAS 32bit to a SAS 64 bit install and sas wasn't able to convert their 32 bit catalog files (🙄). This way you can import them with `readsas`.

**Comment by vpprasanth** [comment]
Thanks @JanMarvin
